### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by esobczak1970** [tabulate/tabulate#34] opened 2016-06-05 23:10 UTC
Fatal error: Uncaught Error: Call to a member function get_record() on boolean in /home/execut61/public_html/charterfishingnow.com/wp-content/plugins/tabulate/src/DB/Reports.php:70 Stack trace: #0 /home/execut61/public_html/charterfishingnow.com/wp-content/plugins/tabulate/src/Controllers/ReportsController.php(30): WordPress\Tabulate\DB\Reports->get_template(1) #1 /home/execut61/public_html/charterfishingnow.com/wp-content/plugins/tabulate/src/Menus.php(140): WordPress\Tabulate\Controllers\ReportsController->index(Array) #2 /home/execut61/public_html/charterfishingnow.com/wp-includes/plugin.php(525): WordPress\Tabulate\Menus->dispatch('') #3 /home/execut61/public_html/charterfishingnow.com/wp-settings.php(393): do_action('init') #4 /home/execut61/public_html/charterfishingnow.com/wp-config.php(99): require_once('/home/execut61/...') #5 /home/execut61/public_html/charterfishingnow.com/wp-load.php(37): require_once('/home/execut61/...') #6 /home/execut61/public_html/charterfishingnow.com/wp-admin/admin.php(31): require_once in /home/execut61/public_html/charterfishingnow.com/wp-content/plugins/tabulate/src/DB/Reports.php on line 70

On version 4.5.2 went to Reports but I don't see any Views or Reports on the previous screen so perhaps it doesn't handle if someone doesn't have reports.

**Comment by samwilson** [comment] 2016-07-14 08:12
This might be an activation issue. Could you try deactivating and then reactivating Tabulate (not uninstalling) and then navigating to *Reports* again?

Sorry for this trouble, and thanks for taking the time to report issues!

**Comment by samwilson** [comment] 2016-09-19 01:17
Closing as not reproducible.

**Comment by altrovideo** [comment] 2016-11-27 21:38
Hi, I've the same problem after clicking `Reports` white page with `Fatal error: Call to a member function get_record() on boolean in /var/www/wordpress.dev/www/wp-content/plugins/tabulate/src/DB/Reports.php on line 70`

I've tried deactivating and reactivating the plugin.

Local install WP 4.7 beta
OS Debian stretch/sid
web server nginx 1.10.2
PHP Version: 5.6.27-0+deb8u1
Databse:	MariaDB
Version: 10.0.28-MariaDB-2 Debian unstable

**Comment by samwilson** [comment] 2016-11-27 23:43
Hi @altrovideo sorry for the trouble!

Does the `<prefix>_tabulate_reports` table exist in your installation? Do you get this error when you're logged in as an admin and/or a lower-privileged user? Are there any errors when activating Tabulate?

I'll investigate further as well.

**Comment by altrovideo** [comment] 2016-11-28 10:32
I see `<prefix>_tabulate_changesets ` and `<prefix>_tabulate_changes` but not the one you asked for.

I'me logget as administrator, no errors displayed when activating Tabulate, wp-debug = true

**Comment by samwilson** [comment] 2017-03-25 08:36
Hm, this is tricky. Activating the plugin is supposed to create the required tables, but it looks like it's not in your case.

I seems that the longer-term solution to this is for Tabulate to check its environment at other times, and act accordingly (c.f. [this](https://core.trac.wordpress.org/ticket/14170#comment:68) that says "Activation hooks are lame, particularly in a network situation. It's far better to use an upgrade routine fired on admin_init, and handle that per-site, basing it on a stored option.")

I've not yet figured out why it might be failing to create the reports table on activation.

**Comment by samwilson** [comment] 2017-04-23 07:14
The recent updates to the activation process have fixed this problem. Please open a new issue if you're still getting this (or any other) bug.

Thanks!

**Closed by samwilson** 2017-04-23 07:14 UTC
Labels: bug, unable to reproduce
